# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
