# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set([('category', 'name')]),
        ),
    ]
