# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20160516_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
