# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20160624_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='index',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='index',
        ),
    ]
