# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import questions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20160508_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='figure',
            field=models.FileField(blank=True, null=True, upload_to=questions.utils.upload_location),
        ),
        migrations.AddField(
            model_name='question',
            name='option_A',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_B',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_C',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_D',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
