# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20160510_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_E',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option_A',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_B',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_C',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_D',
            field=models.CharField(max_length=300),
        ),
    ]
