# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20160510_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
