# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20160510_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=1000),
        ),
    ]
