# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20160513_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_explanation',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_letter',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
