# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20160519_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionresponse',
            old_name='result',
            new_name='correct',
        ),
    ]
