# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20160519_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_C',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_D',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_E',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
