# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20160524_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('number', 'course')]),
        ),
    ]
