# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20160527_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
