# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20160527_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='number',
            new_name='index',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('index', 'course')]),
        ),
    ]
