# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20160601_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='attempt',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together=set([('user', 'question')]),
        ),
    ]
