# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20160602_0515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['course', '-index']},
        ),
    ]
