# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
