# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20160515_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='description',
            field=models.TextField(default='', max_length=2000, null=True),
        ),
    ]
