# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_json_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='json_file',
            new_name='course_json_file',
        ),
    ]
