# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-29 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_question_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='slug',
            field=models.SlugField(default='default-slug'),
        ),
    ]
