# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-29 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_coursesection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
