# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160507_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(choices=[(b'ARTS', b'Arts and Humanities'), (b'BUSINESS', b'Accounting, Finance, and Business'), (b'LGS', b'Legal Studies'), (b'HEALTH_MEDICINE', b'Public Health and Medicine'), (b'IDS', b'Multi-/Interdisciplinary Studies'), (b'PSS', b'Public and Social Services'), (b'STM', b'Science and Math'), (b'ENG', b'Engineering'), (b'SS', b'Social Science'), (b'TPS', b'Trades and Personal Services'), (b'OTHER_MAJOR', b'Unlisted Major')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university',
            field=models.CharField(choices=[(b'CAL', b'UC Berkeley'), (b'UCLA', b'UCLA'), (b'UCD', b'UC Davis'), (b'UCI', b'UC Irvine'), (b'UCSC', b'UC Santa Cruz'), (b'UCSD', b'UC San Diego'), (b'UCSB', b'UC Santa Barbara'), (b'UCR', b'UC Riverside'), (b'UCM', b'UC Merced'), (b'SJSU', b'San Jose State'), (b'Harvard', b'Harvard'), (b'Princeton', b'Princeton'), (b'Columbia', b'Columbia'), (b'Cornell', b'Cornell'), (b'Yale', b'Yale'), (b'Brown', b'Brown'), (b'Dartmouth', b'Dartmouth'), (b'UPENN', b'University of Pennsylvania'), (b'Duke', b'Duke'), (b'Unlisted', b'Unlisted University')], max_length=100, null=True),
        ),
    ]
