# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160507_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(choices=[(b'LSAT', b'LSAT'), (b'GRE', b'GRE')], max_length=120, verbose_name='Course'),
        ),
    ]
