# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160507_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='motivational_image',
            field=models.FileField(blank=True, null=True, upload_to=users.utils.upload_location, verbose_name='Motivational Image'),
        ),
    ]
