# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20160515_0014'),
        ('users', '0011_auto_20160508_1515'),
    ]

    operations = [
    ]
