# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='next_question_index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
