# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20160721_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
