# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 01:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 1, 25, 35, 173817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 1, 25, 35, 174075, tzinfo=utc)),
        ),
    ]
