# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20160814_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 1, 30, 47, 366592, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 1, 30, 47, 366970, tzinfo=utc)),
        ),
    ]
