# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 04:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20160815_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_ended',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 1, 4, 31, 53, 873239, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 1, 4, 31, 53, 873791, tzinfo=utc)),
        ),
    ]
